name: bioinfo
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - biopython
  - pandas
  - matplotlib
  - numpy
  - fastqc
  - multiqc
  - trimmomatic
  - hisat2
  - salmon
  - seqkit
  - samtools
  - bwa
  - blast
  - pip